features:
  numerical:
    - "N"
    - "P"
    - "K"
    - "pH"
    - "Temperature"
    - "Humidity"
    - "Rainfall"
    - "OC"
    - "EC"
    - "B"
    - "Fe"
    - "Mn"
    - "Cu"
    - "Zn"
    - "S"
    - "District_Normal_Rainfall"
    - "N_P_Ratio"
    - "N_K_Ratio"
    - "P_K_Ratio"
    - "Rainfall_Deviation"
    - "Soil_Health_Score"
  categorical:
    - "Soil_Color"
    - "District"
    - "Growing_Season"
    - "OC_Class"
  target: "Crop"
  ignored:
    - "Fertilizer"
